### ISSUE TITLE
Doesn't depend on puppeteer

### ISSUE THREAD

**Issue by stuartlangridge** [humanwhocodes/print-ready#3]
As far as I can tell, puppeteer is a dependency, not a devDependency? 

```bash
$ npm install @humanwhocodes/print-ready --save
[snip some warnings]
+ @humanwhocodes/print-ready@0.1.0
added 35 packages from 53 contributors and audited 35 packages in 1.725s
$ ls
node_modules  package.json  package-lock.json
$ ls node_modules/.bin/
print-ready
$ ./node_modules/.bin/print-ready /path/to/my/file.html -o here.pdf
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'puppeteer' imported from /.../printready/node_modules/@humanwhocodes/print-ready/dist/cli.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

A quick `npm install --save puppeteer` works, and I can see from `package.json` that puppeteer is listed as a `devDependency`, but I'm not looking to develop print-ready, just use it, and I still need puppeteer, I think. So it's a dependency.

**Comment by nzakas** [comment]
Yup, you're correct. Masked by the fact that I have Puppeteer installed everywhere.
